---
- name: Ensure Node.js and npm are installed.
  yum: name=npm state=present enablerepo=epel

- name: Install additional defined npm global packages.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  with_items: nodejs_npm_packages
